// Embeds each module's versioned prompt files into prompts/index.ts, so the app bundle carries them
// and nothing is read from disk at runtime. `--check` fails if a generated file is out of date.
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const check = process.argv.includes("--check");
const stale = [];
for (const schulart of readdirSync("modules", { withFileTypes: true }).filter((d) => d.isDirectory())) {
  for (const klasse of readdirSync(join("modules", schulart.name), { withFileTypes: true }).filter((d) => d.isDirectory())) {
    for (const mod of readdirSync(join("modules", schulart.name, klasse.name), { withFileTypes: true }).filter((d) => d.isDirectory())) {
      const dir = join("modules", schulart.name, klasse.name, mod.name, "prompts");
      if (!existsSync(dir)) continue;
      const files = readdirSync(dir).filter((f) => /\.v\d+\.md$/.test(f)).sort();
      const entries = files.map((f) => `  ${JSON.stringify(f)}: ${JSON.stringify(readFileSync(join(dir, f), "utf8"))},`);
      const out = `// Generated by scripts/gen-prompts.mjs from the .md files in this directory. Do not edit.\nexport const PROMPTS: Record<string, string> = {\n${entries.join("\n")}\n};\n`;
      const target = join(dir, "index.ts");
      const current = existsSync(target) ? readFileSync(target, "utf8") : "";
      if (current === out) continue;
      if (check) stale.push(target);
      else writeFileSync(target, out);
    }
  }
}
if (stale.length) {
  console.error(`Out of date, run "pnpm prompts:gen":\n${stale.join("\n")}`);
  process.exit(1);
}
console.log(check ? "Prompt files up to date." : "Prompt files generated.");
